FORMAT: 1A

# udder
Udder API is a *content management* service for Udder CMS.
Loosely based on _application/vnd.mason+json_ media type.

NOTE: This document is a **work in progress**.

##Allowed HTTPs requests:

- `POST` - Creates or updates a resource
- `PUT` - Updates a resource
- `GET` - Retrieves a resource or list of resources
- `DELETE` - Delete a resource

##Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead).
- 201 `Created` - The request was successful and a resource was created.
- 204 `No Content` - The request was successful but there is no representation to return (that is, the response is empty).
- 400 `Bad Request` - The request could not be understood or was missing required parameters.
- 401 `Unauthorized` - Authentication failed or user does not have permissions for the requested operation.
- 403 `Forbidden` - Access denied.
- 404 `Not Found` - Resource was not found.
- 405 `Method Not Allowed` - Requested method is not supported for the specified resource.
- 429 `Too Many Requests` - Exceeded GoodData API limits. Pause requests, wait one minute, and try again. 
- 503 `Service Unavailable` - The service is temporary unavailable (e.g. scheduled Platform Maintenance). Try again later.

## Main endpoint [/]
### Get main information [GET]

+ Request (application/json)

+ Response 200
    + Body
    
        ```js
            {
                "@namespaces":{
                "ud":{
                    "name": "http://udder.wearegoat.uk/reltypes"
                    }   
                },
                "@meta": {
                    "@name": "Project List",
                    "@description": "List of all projects."
                
                },
                "@links": {
                    "self": { "href": "http://udder.wearegoat.uk/", "title": "Udder" },
                    "ud:projects": { "href": "http://udder.wearegoat.uk/projects", "title": "Projects" },
                    "ud:users": { "href": "http://udder.wearegoat.uk/users", "title": "Users" },
                    "ud:settings": { "href": "http://udder.wearegoat.uk/settings", "title": "Settings" },
                    "start": { "href": "http://udder.wearegoat.uk/projects", "title": "Projects" }
                }
            }
        ```
        

# Group Projects
Project related resources

## Project [/projects/{projectId}]
Single project

---  
**Project attributes:**  
   
- _id `(ObjectId)` : unique identifier.   
- name `(String)` : Project name.  
- description `(String)` : Project description.  
- data `(Object)` : Additional project data.
- metaData `(???)` : Metadata (format???)
- gaCode `(String)` : Google analytics code
- social `(Array)` : Social tokens(???)
   
---  

+ Parameters
    + projectId (required, string, `1`) ... The id of the project

+ Model

    ```js
        {
            "@namespaces":{
            "ud":{
                "name": "http://udder.wearegoat.uk/reltypes"
                }
            },
            "@meta": {
                "@name": "Project List",
                "@description": "List of all projects."
                
            },
            "_id": "1",
            "name": "Fish4Tomorrow",
            "description": "Website for fish4tomorrow",
            "data": {
                "metaData": "What is going to be here?",
                "gaCode": "code blablabla",
                "social": [
                    {
                        "facebook": { "token": "" }
                    }
                ]
            },
            "@links": [
                {"rel": "self", "href": "http://udder.wearegoat.uk/projects/1", "title": "Project details" },
                {"rel": "ud:narratives", "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Project narrative collections" },
                {"rel": "ud:users", "href": "http://udder.wearegoat.uk/users", "title": "Users" },
                {"rel": "ud:settings", "href": "http://udder.wearegoat.uk/settings", "title": "Settings" },
                {"rel": "up", "href": "http://udder.wearegoat.uk/projects", "title": "Projects" },
                {"rel": "start", "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Projects" }
            ],
            @actions: [
                "ud:modify": {
                    "type": "application/json-patch+json",
                    "href": "http://udder.wearegoat.uk/projects/1",
                    "method": "PATCH",
                    "prompt": "Modify project",
                    "template": [
                        {
                            "name": "title", 
                            "value": "", 
                            "prompt": "New project title", 
                            "type": "text", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "description", 
                            "value": "", 
                            "prompt": "New project description", 
                            "type": "textarea", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "gaCode",
                            "value": "",
                            "prompt": "Google analytics code",
                            "type": "text",
                            "valid": [
                                { "required": false },
                                { "maxlength": 15 },
                                { "autocomplete": false }
                            ]
                        }
                    ]
                }
            ]
            
        }
    ```

### Get a project [GET]

+ Request (application/json)

+ Response 200

    [Project][]

### Modify a project [PATCH]

+ Request (application/json-patch+json)

    + Body
        
        ```js
            [{ "op": "add", "path": "/name", "value": "Changed name" },
            { "op": "add", "path": "/description", "value": "Changed description" }]
        ```
        
+ Response 200 (application/json)

    ```js
        {
            "@namespaces":{
            "ud":{
                "name": "http://udder.wearegoat.uk/reltypes"
                }
            },
            "@meta": {
                "@name": "Project List",
                "@description": "List of all projects."
                
            },
            "_id": "1",
            "name": "Changed name",
            "description": "Changed description",
            "@links": [
                {"rel": "self", "href": "http://udder.wearegoat.uk/projects/1", "title": "Project details" },
                {"rel": "ud:narratives", "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Project narrative collections" },
                {"rel": "ud:users", "href": "http://udder.wearegoat.uk/users", "title": "Users" },
                {"rel": "ud:settings", "href": "http://udder.wearegoat.uk/settings", "title": "Settings" },
                {"rel": "up", "href": "http://udder.wearegoat.uk/projects", "title": "Projects" },
                {"rel": "start", "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Projects" }
            ]
        }
    ```
    
## Projects collection [/projects]
Projects collection is the root endpoint for users 
who have more than one project associated with them.

+ Model (application/json)

    ```js
        {
            "@namespaces":{
            "ud":{
                "name": "http://udder.wearegoat.uk/reltypes"
                }
            },
            "@meta": {
                "@title": "Project List",
                "@description": "List of all projects."
            },
            "projects": [
                {
                    "_id": "1",
                    "title": "Fish4Tomorrow",
                    "description": "Website for fish4tomorrow",
                    "data": {
                        "metaData": "What is going to be here?",
                        "gaCode": "code blablabla",
                        "social": [
                            {
                                "facebook": { "token": "1212" }
                            }
                        ]
                    },
                    "@links": {
                        "self": { "href": "http://udder.wearegoat.uk/projects/1", "title": "Project details" },
                        "ud:narratives": { "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Project narrative collections" }
                    }
                },
                {
                    "_id": "2",
                    "title": "Paul Furey: Main",
                    "description": "Main website for Paul Furey",
                    "data": {
                        "metaData": "What is going to be here?",
                        "gaCode": "code blablabla",
                        "social": [
                            {
                                "facebook": { "token": "1212" }
                            }
                        ]
                    },
                    "@links": {
                        "self": { "href": "http://udder.wearegoat.uk/projects/2", "title": "Project details" },
                        "ud:narratives": { "href": "http://udder.wearegoat.uk/projects/2/narratives", "title": "Project narrative collections" }
                    }
                }
            ],
            "@links": [
                {"rel": "self", "href": "http://udder.wearegoat.uk/projects", "title": "Projects" },
                {"rel": "ud:users", "href": "http://udder.wearegoat.uk/users", "title": "Users" },
                {"rel": "ud:settings", "href": "http://udder.wearegoat.uk/settings", "title": "Settings" },
                {"rel": "start", "href": "http://udder.wearegoat.uk/projects/1", "title": "Projects" }
            ]
            "@actions": {
                "ud:create": {
                    "type": "json",
                    "href": "http://udder.wearegoat.uk/projects",
                    "method": "POST",
                    "prompt": "Create new project",
                    "template": [
                        {
                            "name": "title", 
                            "value": "", 
                            "prompt": "New project title", 
                            "type": "text", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "description", 
                            "value": "", 
                            "prompt": "New project description", 
                            "type": "textarea", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "gaCode",
                            "value": "",
                            "prompt": "Google analytics code",
                            "type": "text",
                            "valid": [
                                { "required": false },
                                { "maxlength": 15 },
                                { "autocomplete": false }
                            ]
                        }
                    ]
                }
            }
        }
    ```

### Get all projects [GET]

+ Request (application/json)

+ Response 200

    [Projects collection][]

### Create a project [POST]

+ Request (application/json)

    + Body
    
        ```js
            {
                "name": "Fish4Tomorrow",
                "description": "Website for fish4tomorrow"
            }
        ```

+ Response 201

    ```js
        {
            "@namespaces":{
            "ud":{
                "name": "http://udder.wearegoat.uk/reltypes"
                }
            },
            "@meta": {
                "@name": "Project List",
                "@description": "List of all projects."
                
            },
            "_id": "1",
            "name": "Fish4Tomorrow",
            "description": "Website for fish4tomorrow",
            "@links": {
                "self": { "href": "http://udder.wearegoat.uk/projects/1", "title": "Project details" },
                "ud:narratives": { "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Project narrative collections" }
            }
        }
    ```

# Group Narratives
Narrative related resources of the **Udder API**

## Narrative Collection [/{projectId}/narratives]

+ Model (application/json)
    + Body
    ```
    {
        "collection": { 
            "version": "1.0",
            "href": {"rel":"self", "href": "http://udder.wearegoat.uk/narratives", "prompt": "Udder"},
            "links": [
                {"rel": "users", "href": "http://udder.wearegoat.uk/users", "prompt": "Users"},
                {"rel": "narratives", "href": "http://udder.wearegoat.uk/narratives", "prompt": "Narratives"},
                {"rel": "users", "href": "http://udder.wearegoat.uk/users", "prompt": "Users"}
            ],
            "properties": {
                "_id": "12",
                
            }
               
        }
    }
    ```
    
### Get all narratives of a project [GET]

+ Parameter
    + projectId (required, string) ... Project Id

+ Request (application/json)


+ Response 200
    
    [Narrative Collection][]


+ Response 400 (application/json)
    + Body
    
            {"error": "blabla"}
    
        

