FORMAT: 1A

# udder
Udder API is a *content management* service for Udder CMS.

# Group Narratives
Narrative related resources of the **Udder API**

## Narrative Collection [/narratives?verbose=true]
+ Model (application/json)
    + Body
    ```
    {
        "collection": { 
            "version": "1.0",
            "href": {"rel":"self", "href": "http://private-88d12-udder.apiary-mock.com/narratives", "prompt": "Udder"},
            "links": [
                {"rel": "users", "href": "http://private-88d12-udder.apiary-mock.com/users", "prompt": "Users"},
                {"rel": "narratives", "href": "http://private-88d12-udder.apiary-mock.com/narratives", "prompt": "Narratives"},
                {"rel": "users", "href": "http://private-88d12-udder.apiary-mock.com/users", "prompt": "Users"}
            ],
            "properties": {
                _id: '12',
                
            }
               
        }
    }
    ```
    
### List all Notes [GET]
+ Response 200
    
    [Narrative Collection][]
        

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
