FORMAT: 1A

# udder
Udder API is a *content management* service for Udder CMS.
Loosely based on _application/vnd.mason+json_ media type.

NOTE: This document is a **work in progress**.


# Group Projects
Project related resources

## Projects collection [/projects]
Projects collection is the root endpoint for users 
who have more than one project associated with them.

+ Model (application/json)

    ```js
        {
            "@namespaces":{
            "ud":{
                "name": "http://udder.wearegoat.uk/reltypes"
                }
            },
            "@meta": {
                "@title": "Project List",
                "@description": "List of all projects."
            },
            "projects": [
                {
                    "_id": "1",
                    "title": "Fish4Tomorrow",
                    "description": "Website for fish4tomorrow",
                    "data": {
                        "metaData": "What is going to be here?",
                        "gaCode": "code blablabla",
                        "social": [
                            {
                                "facebook": { "token": "1212" }
                            }
                        ]
                    },
                    "@links": {
                        "self": { "href": "http://udder.wearegoat.uk/projects/1", "title": "Project details" },
                        "ud:narratives": { "href": "http://udder.wearegoat.uk/projects/1/narratives", "title": "Project narrative collections" }
                    }
                },
                {
                    "_id": "2",
                    "title": "Paul Furey: Main",
                    "description": "Main website for Paul Furey",
                    "data": {
                        "metaData": "What is going to be here?",
                        "gaCode": "code blablabla",
                        "social": [
                            {
                                "facebook": { "token": "1212" }
                            }
                        ]
                    },
                    "@links": {
                        "self": { "href": "http://udder.wearegoat.uk/projects/2", "title": "Project details" },
                        "ud:narratives": { "href": "http://udder.wearegoat.uk/projects/2/narratives", "title": "Project narrative collections" }
                    }
                }
            ],
            "@links": {
                "self" : {"href": "http://udder.wearegoat.uk/projects"}
            },
            "@actions": {
                "ud:createProject": {
                    "type": "json",
                    "href": "http://udder.wearegoat.uk/projects",
                    "method": "POST",
                    "prompt": "Create new project",
                    "template": [
                        {
                            "name": "title", 
                            "value": "", 
                            "prompt": "New project title", 
                            "type": "text", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "description", 
                            "value": "", 
                            "prompt": "New project description", 
                            "type": "textarea", 
                            "valid": [
                                { "required": true }, 
                                { "maxlength": 15 }, 
                                { "autocomplete": false }
                            ]
                        },
                        {
                            "name": "gaCode",
                            "value": "",
                            "prompt": "Google analytics code",
                            "type": "text",
                            "valid": [
                                { "required": false },
                                { "maxlength": 15 },
                                { "autocomplete": false }
                            ]
                        }
                    ]
                }
            }
        }
    ```

### Get all projects [GET]

+ Request (application/json)

+ Response 200

    [Projects collection][]

### Create a project [POST]

+ Request (application/json)

+ Response 201


# Group Narratives
Narrative related resources of the **Udder API**

## Narrative Collection [/{projectId}/narratives]

+ Model (application/json)
    + Body
    ```
    {
        "collection": { 
            "version": "1.0",
            "href": {"rel":"self", "href": "http://udder.wearegoat.uk/narratives", "prompt": "Udder"},
            "links": [
                {"rel": "users", "href": "http://udder.wearegoat.uk/users", "prompt": "Users"},
                {"rel": "narratives", "href": "http://udder.wearegoat.uk/narratives", "prompt": "Narratives"},
                {"rel": "users", "href": "http://udder.wearegoat.uk/users", "prompt": "Users"}
            ],
            "properties": {
                "_id": "12",
                
            }
               
        }
    }
    ```
    
### Get all narratives of a project [GET]

+ Parameter
    + projectId (required, string) ... Project Id

+ Request (application/json)


+ Response 200
    
    [Narrative Collection][]


+ Response 400 (application/json)
    + Body
    
            {"error": "blabla"}
    
        

